[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

## This needs to be set to false
ffi = true # Enable Foreign Function Interface for external calls eg. to scripts 

mappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

fs_permissions = [{ access = "read", path = "./broadcast"}, { access = "read", path = "./img"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
